=== Ruben-BV/lista_de_pokemons/pokemons.dtd
<!ELEMENT pokemons (pokemon+)>
<!ELEMENT pokemon (nombre, tipo, nivel, ataques)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT nivel (#PCDATA)>
<!ELEMENT ataques (ataque+)>
<!ELEMENT ataque EMPTY>
<!ATTLIST ataque nombreAtaque CDATA #REQUIRED>
<!ATTLIST ataque poder CDATA #REQUIRED>

=== Ruben-BV/lista_de_pokemons/pokemons.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pokemons SYSTEM "pokemons.dtd">
<pokemons>
	<pokemon>
		<nombre>Vaporeon</nombre>
		<tipo>agua</tipo>
		<nivel>110</nivel>
		<ataques>
			<ataque nombreAtaque="Agua Lodosa" poder="20"></ataque>
			<ataque nombreAtaque="Drenaje Espiral" poder="60"></ataque>
		</ataques>
	</pokemon>
	<pokemon>
		<nombre>Litten</nombre>
		<tipo>fuego</tipo>
		<nivel>70</nivel>
		<ataques>
			<ataque nombreAtaque="Mordisco" poder="10"></ataque>
			<ataque nombreAtaque="Llama" poder="20"></ataque>
		</ataques>
	</pokemon>
</pokemons>
